{% set name = "jupyterlab-solarized-light-theme" %}
{% set version = "1.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_solarized_light_theme-{{ version }}.tar.gz
  sha256: 0b777e440f897538f7148f278e0e9ec6ae6aa2fa5da0de1b765595abaa0d7e9c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder >=0.5
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - jupyterlab_solarized_light_theme
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/mswolman/jupyterlab-solarized-light-theme
  summary: Solarized light theme for Jupyterlab.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mswolman
